# Generated by Django 4.2.4 on 2023-08-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('classes', '0001_initial'),
        ('class_subject', '0001_initial'),
        ('school_year', '0001_initial'),
        ('user', '0002_user_department_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_quick', models.FloatField(default=0, verbose_name='Kiểm tra miệng')),
                ('exam_15_no_1', models.FloatField(default=0, verbose_name='Kiểm tra 15 phút lần 1')),
                ('exam_15_no_2', models.FloatField(default=0, verbose_name='Kiểm tra 15 phút lần 2')),
                ('exam_15_no_3', models.FloatField(default=0, verbose_name='Kiểm tra 15 phút lần 3')),
                ('exam_15_no_4', models.FloatField(default=0, verbose_name='Kiểm tra 15 phút lần 4')),
                ('exam_45_no_1', models.FloatField(default=0, verbose_name='Kiểm tra 1 tiết lần 1')),
                ('exam_45_no_2', models.FloatField(default=0, verbose_name='Kiểm tra 1 tiết lần 2')),
                ('exam_finally', models.FloatField(default=0, verbose_name='Kiểm tra cuối kì')),
                ('is_section_1', models.BooleanField(default=False, verbose_name='Học kỳ I')),
                ('is_section_2', models.BooleanField(default=False, verbose_name='Học kỳ II')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày cập nhật')),
                ('class_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class_subject.classsubject', verbose_name='Lớp - môn học - giáo viên - năm học - kì học')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Học sinh')),
            ],
            options={
                'verbose_name': 'Điểm',
                'verbose_name_plural': 'Điểm',
                'db_table': 'points',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_score_section_1', models.FloatField(default=0, verbose_name='Điểm tổng kết HK I')),
                ('medium_score_section_2', models.FloatField(default=0, verbose_name='Điểm tổng kết HK II')),
                ('medium_score_overall', models.FloatField(default=0, verbose_name='Điểm tổng kết cả năm học')),
                ('conduct_classification_section_1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Xếp loại hạnh kiểm HK I')),
                ('conduct_classification_section_2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Xếp loại hạnh kiểm HK II')),
                ('conduct_classification_overall', models.CharField(blank=True, max_length=10, null=True, verbose_name='Xếp loại hạnh kiểm cả năm')),
                ('positive_section_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Điểm tốt học kì I')),
                ('positive_section_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Điểm tốt học kì II')),
                ('negative_section_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Điểm chưa tốt học kì I')),
                ('negative_section_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Điểm chưa tốt học kì II')),
                ('days_off_section_1', models.FloatField(default=0, verbose_name='Số ngày nghỉ học HK I')),
                ('days_off_section_2', models.FloatField(default=0, verbose_name='Số ngày nghỉ học HK II')),
                ('days_off_overall', models.FloatField(default=0, verbose_name='Số ngày nghỉ học cả năm học')),
                ('rank_section_1', models.CharField(blank=True, max_length=10, null=True, verbose_name='Học lực HK I')),
                ('rank_section_2', models.CharField(blank=True, max_length=10, null=True, verbose_name='Học lực HK II')),
                ('rank_overall', models.CharField(blank=True, max_length=10, null=True, verbose_name='Học lực cả năm')),
                ('note_overall', models.CharField(blank=True, max_length=500, null=True, verbose_name='Đánh giá chung của giáo viên')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày cập nhật')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes', verbose_name='Lớp học')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_year.schoolyear', verbose_name='Năm học')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student', verbose_name='Học sinh')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Giáo viên chủ nhiệm')),
            ],
            options={
                'verbose_name': 'Tổng kết',
                'verbose_name_plural': 'Tổng kết',
                'db_table': 'performances',
            },
        ),
    ]
