# Generated by Django 4.2.4 on 2023-08-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='avg_point',
            field=models.FloatField(default=0, verbose_name='Trung bình môn'),
        ),
    ]
