# Generated by Django 4.2.4 on 2023-08-13 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_year', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Tên đầy đủ')),
                ('gender', models.CharField(blank=True, max_length=4, null=True, verbose_name='Giới tính')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Ngày tháng năm sinh')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nơi sinh')),
                ('nation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dân tộc')),
                ('religion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tôn giáo')),
                ('father_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên bố')),
                ('father_job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nghề nghiêp bố')),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tên mẹ')),
                ('mother_job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nghề nghiêp mẹ')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày cập nhật')),
                ('classes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes', verbose_name='Lớp')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_year.schoolyear', verbose_name='Năm học')),
            ],
            options={
                'verbose_name': 'Học sinh',
                'verbose_name_plural': 'Học sinh',
                'db_table': 'students',
            },
        ),
    ]
