# Generated by Django 4.2.4 on 2023-08-13 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_user_department_user_password'),
        ('classes', '0001_initial'),
        ('school_year', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_teach_section_1', models.BooleanField(default=True, verbose_name='Học kỳ I')),
                ('can_teach_section_2', models.BooleanField(default=True, verbose_name='Học kỳ II')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày cập nhật')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes', verbose_name='Lớp học')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_year.schoolyear', verbose_name='Năm học')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject', verbose_name='Môn học')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='Giáo viên')),
            ],
            options={
                'verbose_name': 'Lớp học môn học',
                'verbose_name_plural': 'Lớp học môn học',
                'db_table': 'class_subjects',
            },
        ),
    ]
