# Generated by Django 4.2.4 on 2023-08-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tổ')),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Tổ',
                'verbose_name_plural': 'Tổ',
                'db_table': 'departments',
            },
        ),
    ]
