# Generated by Django 4.2.4 on 2023-08-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Khối')),
                ('slug', models.SlugField()),
                ('no', models.IntegerField(blank=True, null=True, verbose_name='Số')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Khối',
                'verbose_name_plural': 'Khối',
                'db_table': 'grades',
            },
        ),
    ]
