# Generated by Django 4.2.4 on 2023-08-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Tên đầy đủ')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Số điện thoại')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('specialize', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chuyên môn')),
                ('position', models.CharField(blank=True, max_length=500, null=True, verbose_name='Chức vụ')),
                ('created_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'users',
            },
        ),
    ]
